version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=super_user
      - POSTGRES_PASSWORD=super_user
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./etc/db/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
